"""Update bsdsdf 

Revision ID: 631016713461
Revises: 
Create Date: 2025-04-27 05:49:51.853926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '631016713461'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('id', sa.String(length=38), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other'), nullable=True),
    sa.Column('status', sa.Enum('active', 'banned'), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=38), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('responses',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('public', 'private'), nullable=True),
    sa.Column('user_id', sa.String(length=38), nullable=False),
    sa.Column('vote', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=38), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_responses_user_id'), ['user_id'], unique=False)

    op.create_table('response_tags',
    sa.Column('response_id', sa.String(length=38), nullable=False),
    sa.Column('tag_id', sa.String(length=38), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], onupdate='cascade', ondelete='cascade'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('response_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response_tags')
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_responses_user_id'))

    op.drop_table('responses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_name'))

    op.drop_table('tags')
    # ### end Alembic commands ###
