"""Updat 

Revision ID: cdd7d9b34787
Revises: 631016713461
Create Date: 2025-04-27 06:25:25.531528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cdd7d9b34787'
down_revision = '631016713461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=mysql.ENUM('male', 'female', 'other'),
               type_=sa.Enum('male', 'female', 'other', name='gender_enum', native_enum=False),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('active', 'banned'),
               type_=sa.Enum('active', 'banned', name='user_status_enum', native_enum=False),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('active', 'banned', name='user_status_enum', native_enum=False),
               type_=mysql.ENUM('active', 'banned'),
               existing_nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.Enum('male', 'female', 'other', name='gender_enum', native_enum=False),
               type_=mysql.ENUM('male', 'female', 'other'),
               existing_nullable=True)

    # ### end Alembic commands ###
